language: c

env:
  global:
    - LUA=lua5.3

branches:
  only:
    - master

install:
  - sudo apt-get install $LUA

script:
  - $LUA tests.lua

notifications:
  recipients:
    - derekmines@gmail.com
  email:
    on_success: change
    on_failure: always