language: c

env:
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - master

install:
  - sudo apt-get install $LUA

script:
  - lua tests.lua

notifications:
  recipients:
    - derekmines@gmail.com
  email:
    on_success: change
    on_failure: always