dist: xenial

language: c

branches:
  only:
    - master

install:
  - sudo apt-get install lua5.3

script:
  - lua5.3 tests.lua

notifications:
  recipients:
    - derekmines@gmail.com
  email:
    on_success: change
    on_failure: always